EasyCredit/Controllers/LoanController.cs
using Biblioteca_app.Extensions;
using DTO;
using EasyCredit.Models;
using Factory;
using Helper;
using SelectPdf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyCredit.Controllers
{
    public class LoanController : Controller
    {
        PdfPageSize PageSize => PdfPageSize.A4;
        PdfPageOrientation PdfOrientation =>PdfPageOrientation.Portrait;
        int WebPageWidth => 1500;
        UsuarioDTO usuario;
        private readonly ClienteHelp _clienteHelp;
        private readonly PrestamoHelp _prestamoHelp;
        private readonly TipoCobroHelp _tipoCobroHelp;
        private readonly TipoPagoHelp _tipoPagoHelp;
        private readonly FormaPagoHelp _formapagoHelp;
        List <PrestamoDTO> prestamos;
        public LoanController(FormaPagoHelp formaPagoHelp, ClienteHelp clienteHelp,PrestamoHelp prestamoHelp,
            TipoCobroHelp tipoCobroHelp,TipoPagoHelp tipoPagoHelp)
        {
            _formapagoHelp= formaPagoHelp;
            _clienteHelp = clienteHelp;
            _prestamoHelp = prestamoHelp;
            _tipoCobroHelp = tipoCobroHelp;
            _tipoPagoHelp = tipoPagoHelp;
        }
        [HttpGet]
        // GET: Loan
        public ActionResult Index(string identificacion)
        {
            usuario = (UsuarioDTO)Session["Usuario"];
            if (usuario == null)
            {
                return RedirectToAction("Login", "Employee");
            }
            ViewBag.usuario = usuario;
            ViewBag.EmpleadoId =usuario.Empleados[0].Id ;
            ViewBag.Tipocobro=_tipoCobroHelp.TEntity.ToList();
            if (string.IsNullOrEmpty(identificacion))
            { 
                List<Message> messages = new List<Message>
                {
                    new Message { IsSuccess = false, Text = "Por favor ingrese una identificación." }
                };
                TempData["error"] = messages;
                prestamos = _prestamoHelp.TEntity.ToList(); 
                return View(prestamos );
            }
            var cliente = _clienteHelp.TEntity.Where(x => x.Identificacion == identificacion).FirstOrDefault();
            if (cliente == null)
            {
                prestamos = _prestamoHelp.TEntity.ToList();
                List<Message> messages = new List<Message>
                    {
                        new Message { IsSuccess = false, Text = "Cliente no encontrado." }
                    };
                TempData["error"] = messages;
                return View(prestamos);
            }
            prestamos = _prestamoHelp.TEntity.Where(x=>x.ClienteId==cliente.Id) .ToList();
            ViewBag.Cliente = cliente;
            return View(prestamos);
        }

        [HttpGet]
        // GET: Loan/Details/5
        public ActionResult Details(int id)
        {
            usuario = (UsuarioDTO)Session["Usuario"];
            if (usuario == null)
            {
                return RedirectToAction("Login", "Employee");
            }
            ViewBag.usuario = usuario;
            ViewBag.FormasPagos = _formapagoHelp.TEntity.ToList();
            ViewBag.TipoPagos = _tipoPagoHelp.TEntity.ToList();
            var prestamo = _prestamoHelp.TEntity.Where(z=>z.Id==id).FirstOrDefault();
            return View(prestamo);
        }

        // GET: Loan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Loan/Create
        [HttpPost]
        public JsonResult Create(PrestamoDTO prestamoDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (prestamoDTO.Id != 0)
                    {
                       _prestamoHelp. Actualizar(prestamoDTO.Id, prestamoDTO);
                        return Json(new { data = "El registro se ha actualizado" }, JsonRequestBehavior.AllowGet);
                    }
                    _prestamoHelp.Guardar(prestamoDTO);
                    return Json(new { data = "Has registrado un prestamo" }, JsonRequestBehavior.AllowGet);

                }
                var errors= ModelState.Values.SelectMany(x => x.Errors).Select(e => new Message
                {
                    Text = e.ErrorMessage,
                    IsSuccess = false
                }).ToList();
                TempData["Error"] = errors;
                // TODO: Add insert logic here

                return Json(new { data = errors }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex) 
            {
                var errors = new List<Message> {
                    new Message {
                         Text = ex.Message,
                    IsSuccess = false
                    }
                };
                TempData["Error"] = errors;
                return Json(new { data = errors }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Loan/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Loan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult PayHistorial(int idprestamo)
        {
            usuario = (UsuarioDTO)Session["Usuario"];
            if (usuario == null)
            {
                return RedirectToAction("Login", "Employee");
            }
            ViewBag.Empresa = usuario.Empleados[0].EmpresaDTO;
            var prestamo=   _prestamoHelp.TEntity.Where(x=>x.Id ==idprestamo).FirstOrDefault();
          //  string htmlString = this.RenderRazorViewToString("PayHistorial", prestamo );
            //PdfPageSize pageSize = PdfPageSize.A4;
            //PdfPageOrientation pdfOrientation = PdfPageOrientation.Portrait;
           // int webPageWidth = 1500;
            byte[] pdf = _prestamoHelp.ExportarPdf(this, "PayHistorial", prestamo, PageSize, PdfOrientation, WebPageWidth);

            return File(pdf, "application/pdf"); 
            
        }
        public ActionResult LoanHistorial()
        {
            usuario = (UsuarioDTO)Session["Usuario"];
            if (usuario == null)
            {
                return RedirectToAction("Login", "Employee");
            }
            
            ViewBag.Empresa = usuario.Empleados[0].EmpresaDTO;
            int id = usuario.Empleados[0].Id;
            var prestamos  = _prestamoHelp.TEntity.Where(x => x.EmpleadoId == id ).ToList();
         //   string htmlString = this.RenderRazorViewToString("LoanHistorial", prestamos);         
            byte[] pdf = _prestamoHelp.ExportarPdf(this, "LoanHistorial",prestamos , PageSize,PdfOrientation,WebPageWidth);
            return File(pdf, "application/pdf");                
        }

        // GET: Loan/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Loan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EasyCredit/Views/Loan/Details.cshtml
@model DTO.PrestamoDTO

@{
    ViewBag.Title = "Details";
   DTO.UsuarioDTO usuario = ViewBag.usuario;
    List<Factory.FormaPago> formaPagos = (List<Factory.FormaPago>)ViewBag.FormasPagos;
    List<Factory.TipoPago> tipoPagos = (List<Factory.TipoPago>)ViewBag.TipoPagos;
    string refe = DateTime.Now.ToOADate().ToString();
}

<h2>Detalles</h2>
<div class="card mb-4">
    <div class="card-header">
        <i class="fa-solid fa-circle-info"></i>
        Informacion General
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-4">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Referencia)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Referencia)
                    </dd>
                </dl>
            </div>
            @if (Model.Fiador != null)
            {
                <div class="col-4">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Fiador.Identificacion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Fiador.Identificacion)
                        </dd>
                    </dl>
                </div>
            }
            <div class="col-4">
                <dl class="dl-horizontal">
                    <dt>
                        Cliente
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Cliente.NombreCompleto)
                    </dd>
                </dl>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <dl>
                    <dt>
                        Empleado
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Empleado.NombreCompleto)
                    </dd>

                </dl>
            </div>
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Estado.Nombre)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Estado.Nombre)
                    </dd>
                </dl>
            </div>
            <div class="col-4">
                <dl>

                    <dt>
                        @Html.DisplayNameFor(model => model.Modo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Modo)
                    </dd>
                </dl>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Monto)
                    </dt>

                    <dd>
                        @Model.Monto.ToString("C0")
                    </dd>
                </dl>
            </div>
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Tiempo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Tiempo)
                    </dd>
                </dl>
            </div>
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Interes)
                    </dt>

                    <dd>
                        @Model.Interes.ToString("#'%'")
                    </dd>
                </dl>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Fecha)
                    </dt>

                    <dd>
                        @Model.Fecha.ToString("yyyy-MM-dd")
                    </dd>
                </dl>
            </div>
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Observacion)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Observacion)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        <i class="fa-solid fa-comments-dollar"></i>
        Detalles del prestamo
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <table id="datatablesSimple" class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Periodo</th>
                            <th>Referencia</th>
                            <th>Fecha</th>
                            <th>Valor</th>
                            <th>Abonos</th>
                            <th>Saldo</th>

                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model.Amortizacions)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Periodo</td>
                        <td>@item.Referencia</td>
                        <td>@item.Fecha.ToString("yyyy/MM/dd")</td>
                        <td>@String.Format("{0:C0}", item.Valor)</td>
                        <td>@String.Format("{0:C0}", item.Abono) </td>
                        <td>@String.Format("{0:C0}", item.Valor - item.Abono)</td>

                        <td>
                            @if (!item.PagoCompleto)
                            {
                                <button title="pagar cuotas" onclick="Pagar(@item.Id)" class="btn btn-primary">
                                    <i class="fa-solid fa-cash-register"></i>
                                </button>
                            }
                        </td>
                        <td>
                            <a title="Detalles de pagos" href="@Url.Action("index", "pay", new { CuotaId = item.Id })" class="btn btn-info">
                                <i class="fa-solid fa-eye"></i>
                            </a>
                        </td>
                    </tr>
                }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Total)
                    </dt>

                    <dd>
                        @Model.Total.ToString("C0")
                    </dd>
                </dl>
            </div>
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.TotalAmortizado)
                    </dt>

                    <dd>
                        @Model.TotalAmortizado.ToString("C0")
                    </dd>
                </dl>
            </div>
            <div class="col-4">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Saldo)
                    </dt>

                    <dd>
                        @Model.Saldo.ToString("C0")
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>
<div>
    <p>
        <a href="@Url.Action("Index","Loan",new { identificacion = Model.Cliente.Identificacion })" class="btn btn-primary"><i class="fa-solid fa-house"></i></a>
        <a target="_blank" class="btn btn-danger" href="@Url.Action("PayHistorial","Loan",new { idprestamo=Model.Id })"><i class="fa-solid fa-file-pdf"></i></a>


    </p>
 </div>
        <div id="Pays">
            <form action="@Url.Action("create","pay")" id="payAdd" autocomplete="off" method="post">
                <input type="hidden" id="AmortizacionId" name="AmortizacionId" />
                <input type="hidden" id="EmpleadoId" name="EmpleadoId" value="@usuario.Empleados[0].Id" />
                <div class="form-group">
                    <label for="Referencia">Referencia</label>
                    <input type="text" id="Referencia" name="Referencia" value="@refe" readonly class="form-control" />
                </div>
                <div class="form-group">
                    <label for="Fecha">Fecha</label>
                    <input type="date" id="Fecha" name="Fecha" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="Referencia">Pago Maximo</label>
                    <input type="text" id="pagoMaximo" disabled name="pagoMaximo" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="ValorPagar">Valor a Pagar</label>
                    <input type="number" step="0.01" id="ValorPagar" name="ValorPagar" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="Observaciones">Observaciones</label>
                    <textarea id="Observaciones" name="Observaciones" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="FormaPagoId">Forma de Pago</label>
                    <select id="FormaPagoId" name="FormaPagoId" class="form-select">
                        <option value="">-- Seleccione una forma de pago --</option>
                        @foreach (var formaPago in formaPagos)
                        {
                            <option value="@formaPago.Id">@formaPago.Nombre</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="TipoPagoId">Tipo de Pago</label>
                    <select id="TipoPagoId" name="TipoPagoId" class="form-select">
                        <option value="">-- Seleccione un tipo de pago --</option>
                        @foreach (var tipoPago in tipoPagos)
                        {
                            <option value="@tipoPago.Id">@tipoPago.Nombre</option>
                        }
                    </select>
                </div>
            </form>
        </div>

EasyCredit/Views/Loan/LoanHistorial.cshtml
@model IEnumerable<DTO.PrestamoDTO>
@{
    Layout = "~/Views/Shared/_layoutPdf.cshtml";
}
<h2>Listado de prestamos</h2>
<table  class="table ui-widget ui-widget-content">
    <thead>
        <tr class="ui-widget-header">
            <th>
                Cliente
            </th>          
            <th>
                @Html.DisplayNameFor(model => model.Referencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Monto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Interes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tiempo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.TotalAmortizado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Saldo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente.NombreCompleto)
                </td>                
                <td>
                    @Html.DisplayFor(modelItem => item.Referencia)
                </td>
                <td>
                    @item.Monto.ToString("C0")
                </td>
                <td>
                    @item.Interes.ToString("#'%'")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tiempo)
                </td>
                <td>
                    @item.Fecha.ToString("yyyy/MM/dd")
                </td>
                <td>@item.Cuota.ToString("C0")</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modo)
                </td>
                <td>
                    @item.Total.ToString("C0")
                </td>
                <td>
                    @item.TotalAmortizado.ToString("C0")
                </td>
                <td>
                    @item.Saldo.ToString("C0")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado.Nombre)
                </td>
                
            </tr>
        }
    </tbody>

</table>

EasyCredit/Views/Loan/index.cshtml
@model IEnumerable<DTO.PrestamoDTO>

@{

    ViewBag.Title = "index";
    DTO.ClienteDTO clienteDTO = (DTO.ClienteDTO)ViewBag.Cliente;
    int empleadoId = (int)ViewBag.EmpleadoId;
    List<Factory.TipoCobro> tipoCobros = ViewBag.Tipocobro;
    int clienteId = 0;
    string codigo = DateTime.Now .ToOADate().ToString();
    if (clienteDTO != null)
    {
        clienteId = clienteDTO.Id;
        codigo = codigo + clienteDTO.Identificacion;

    }
}

<h2>Listado de prestamos</h2>

@if (clienteDTO != null)
{
    @Html.Partial("_SearchCliente", clienteDTO)
}
else
{
    <div class="card mb-4">
        <div class="card-header">
            <i class="fa-solid fa-user"></i>
            Busqueda de Cliente
        </div>
        <div class="card-body">
            <form autocomplete="off" action="@Url.Action("index","Loan")" method="get" class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">                    
                    <input id="identificacion" name="identificacion" class="form-control" type="text" placeholder="Identificación del Cliente" aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button type="submit" class="btn btn-primary" id="btnNavbarSearch"><i class="fas fa-search"></i></button>
                </div>
            </form>            
        </div>
    </div>

}
<table id="datatablesSimple" class="table">
    <thead>
        <tr>
            <th>
                Cliente
            </th>
            <th>
                Empleado
            </th>
            <th>
                Fiador
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Referencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Monto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Interes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tiempo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.TotalAmortizado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Saldo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>           
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente.NombreCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Empleado.NombreCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fiador.NombreCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Referencia)
                </td>
                <td>
                    @item.Monto.ToString("C0")
                </td>
                <td>
                   @item.Interes.ToString("#'%'")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tiempo)
                </td>
                <td>
                    @item.Fecha.ToString("yyyy/MM/dd")
                </td>
                <td>@item.Cuota.ToString("C0")</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modo)
                </td>
                <td>
                    @item.Total.ToString("C0")
                </td>
                <td>
                    @item.TotalAmortizado.ToString("C0")
                </td>
                <td>
                    @item.Saldo.ToString("C0")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado.Nombre)
                </td>
                <td>
                    <a title="Ver detalles" class="btn btn-info" href="@Url.Action("Details", "loan", new { id = item.Id })">
                        <i class="fa-solid fa-comment-dollar"></i>
                    </a>
                </td>
                <td>
                    <form onsubmit="return validar('Desea eliminar el Prestamo?')" action="@Url.Action("delete","loan")" method="post">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button title="Eliminar prestamo" class="btn btn-danger" type="submit"><i class="fa-solid fa-trash"></i></button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

</table>
<p>
    <button class="btn btn-primary" title="Crear prestamo" onclick="CrearPrestamo(); "><i class="fa-solid fa-landmark"></i></button>
    <a target="_blank" class="btn btn-danger" href="@Url.Action("LoanHistorial","Loan")"><i class="fa-solid fa-file-pdf"></i></a>

</p>
<div id="loans">
    <input type="hidden" name="codigo" id="codigo" value="@codigo" />
    <input type="hidden" name="clienteId" id="clienteId" value="@clienteId" />
    <input type="hidden" name="empleadoId" id="empleadoId" value="@empleadoId" />
    <div class="row">
        <div class="col-6">
            <div class="mb-3">
                <label class="form-label" for="monto">
                    Fiador
                </label>
                <input type="text" class=" form-control" name="fiador" value="" id="fiador" />
            </div>

            <div class="mb-3">
                <label class="form-label" for="monto">
                    Fecha
                </label>
                <input type="date" class=" form-control" name="fecha" value="" id="fecha" />
            </div>
            <div class="mb-3">
                <label class="form-label" for="monto">
                    Monto
                </label>
                <input type="number" class=" form-control" name="monto" value="" id="monto" />
            </div>

            <div class="mb-3">
                <label class="form-label" for="monto">
                    Porcentaje
                </label>
                <input type="number" class=" form-control" name="porcentaje" value="" id="porcentaje" />
            </div>

            <div class="mb-3">
                <label class="form-label" for="monto">
                    Tiempo
                </label>
                <input type="number" class=" form-control" name="tiempo" value="" id="tiempo" />
            </div>
            <div class="mb-3">
                <label class="form-label" for="monto">
                    Tipo cobro
                </label>
                <select class="form-select" id="tipocobro" name="tipocobro">
                    <option value=""> seleccione una opcion</option>
                    @foreach (var item in tipoCobros)
                    {
                        <option value="@item.Id">@item.Nombre  </option>
                    }
                </select>
            </div>
            <button class="btn btn-success" id="cuotas">Generar cuotas</button>
        </div>
        <div class="col-6">
            <div class="mb-3">
                <label class="form-label" for="monto">
                    Cuota
                </label>
                <input type="text" class=" form-control" name="cuota" value="" id="cuota" />
            </div>
            <div class="mb-3">
                <label class="form-label" for="monto">
                    Total                    
                </label>
                <input type="text" class=" form-control" name="Total" value="" id="Total" />   
            </div>

            <table class="table" id="tblCuota">
                <thead>
                    <tr>
                        <th>Periodo</th>
                        <th>Referencia</th>
                        <th>Fecha</th>
                        <th>Valor</th>

                    </tr>
                </thead>
                <tbody style="overflow-y:scroll; height:100px">
                </tbody>
            </table>
        </div>
    </div>

</div>