EasyCredit/Controllers/ClientController.cs
using DTO;
using EasyCredit.Models;
using Factory;
using Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyCredit.Controllers
{
    public class ClientController : Controller
    {
        UsuarioDTO usuario;
        TipoIdentificacionHelp tipoIdentificacionHelp;
        ClienteHelp clienteHelp;
        AreaHelp areaHelp;
        TipoTelefonoHelp tipoTelefonoHelp;
        List<Message> errors;
        public ClientController(ClienteHelp clienteHelp,
            TipoIdentificacionHelp tipoIdentificacionHelp,
            AreaHelp areaHelp,
            TipoTelefonoHelp tipoTelefonoHelp)
        {
            this.tipoTelefonoHelp = tipoTelefonoHelp;
            this.clienteHelp = clienteHelp;
            this.tipoIdentificacionHelp = tipoIdentificacionHelp;
            this.areaHelp = areaHelp;
        }
        [HttpGet]
        public JsonResult Search(int id)
        {
            ClienteDTO cliente = clienteHelp.TEntity.Where(x=>x.Id==id).FirstOrDefault();
            return Json(new { data = cliente }, JsonRequestBehavior.AllowGet);
        }
        // GET: Client
        [HttpGet]
        public ActionResult Index()
        {
            usuario = (UsuarioDTO)Session["Usuario"];

            if (usuario == null)
            {
                return RedirectToAction("Login", "Employee");
            }
            ViewBag.usuario = usuario;
            ViewBag.TipoIdentificaciones = tipoIdentificacionHelp.TEntity.ToList();
            ViewBag.Areas = areaHelp.TEntity.ToList();
            List <ClienteDTO> clientes = clienteHelp .TEntity.ToList();
            return View( clientes);
        }

        // GET: Client/Details/5
        [HttpGet]
        public ActionResult Details(int id)
        {
            usuario = (UsuarioDTO)Session["Usuario"];

            if (usuario == null)
            {
                return RedirectToAction("Login", "Employee");
            }
            ViewBag.usuario = usuario;

            ViewBag.TipoIdentificaciones = tipoIdentificacionHelp.TEntity.ToList();
            ViewBag.tipoTelefonos = tipoTelefonoHelp.TEntity.ToList();
            ClienteDTO cliente = clienteHelp.TEntity.Where(x => x.Id == id).FirstOrDefault();
            return View(cliente);
        }        
        // POST: Client/Create
        [HttpPost]
        public ActionResult Create(ClienteDTO clienteDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (clienteDTO.Id != 0)
                    {
                        clienteHelp.Actualizar(clienteDTO.Id, clienteDTO);
                        return RedirectToAction("Index");
                    }
                    clienteHelp.Guardar(clienteDTO);                    
                    return RedirectToAction("Index");
                }
                TempData["Error"] = ModelState.Values.SelectMany(x => x.Errors).Select(e => new Message
                {
                    Text = e.ErrorMessage,
                    IsSuccess = false
                }).ToList();
                return RedirectToAction("Index");
                // TODO: Add insert logic here

            }
            catch (Exception ex)
            {
                errors = new List<Message> {
                    new Message { Text = ex.Message, IsSuccess = false }
                    
                };                
                TempData["Error"] = errors;
                return RedirectToAction("Index");
            }
        }
        // POST: Client/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                clienteHelp.Eliminar(id);            
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                errors = new List<Message>
                {
                    new Message{Text = ex.Message,IsSuccess = false}                    
                };                
                TempData["Error"] = errors;
                return RedirectToAction("Index");
            }
        }
    }
}

EasyCredit/Controllers/ReferencesController.cs
using Helper;
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyCredit.Controllers
{
    public class ReferencesController : Controller
    {
        ReferenciaHelp referenciaHelp;
        List<string> errors;
        public ReferencesController(ReferenciaHelp referenciaHelp)
        {
            this.referenciaHelp = referenciaHelp;
        }
        // GET: References
        public ActionResult Index()
        {
            return View();
        }

        // GET: References/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: References/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: References/Create
        [HttpPost]
        public ActionResult Create(ReferenciaDTO referenciaDTO )
        {
            var url = Url.Action("Details", "client", new { id = referenciaDTO.ClienteId });
            try
            {
                if (ModelState.IsValid)
                {
                    if (referenciaDTO.Id != 0)
                    {
                        referenciaHelp.Actualizar(referenciaDTO.Id, referenciaDTO);
                        return Redirect(url);
                    }
                    referenciaHelp.Guardar(referenciaDTO);
                    return Redirect(url);
                }
                TempData["Error"] = ModelState.Values.SelectMany(x => x.Errors).Select(e => e.ErrorMessage).ToList();
                return Redirect(url);
                // TODO: Add insert logic here
            }
            catch (Exception ex)
            {
                errors = new List<string>
                    {
                        ex.Message
                    };
                TempData["Error"] = errors;
                return Redirect(url);
            }

         
        }

        // GET: References/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: References/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // POST: References/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var url = Url.Action("Details", "client", new { id = collection["ClienteId"] });
            try
            {
                // TODO: Add delete logic here
                referenciaHelp.Eliminar(id);
                return Redirect(url);
            }
            catch (Exception ex)
            {
                errors = new List<string> {
                    ex.Message
                };
                TempData["Error"] = errors;
                return Redirect(url);
                
            }
        }
    }
}

EasyCredit/Views/Client/Details.cshtml
@model DTO.ClienteDTO

@{
    var telefonos = Model.Telefonos;
    List<Factory.TipoTelefono> tipoTelefonos = (List<Factory.TipoTelefono>)ViewBag.tipoTelefonos;
    List<Factory.TipoIdentificacion> tipoIdentificaciones = (List<Factory.TipoIdentificacion>)ViewBag.tipoIdentificaciones;
    ViewBag.Title = "Details";
}
<h4>Detalles de cliente</h4>
<hr />
<div style="padding:10px;">
    <div class="row">
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.Area.Nombre) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Area.Nombre)
            </dd>
        </div>
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.TipoIdentificacion.Nombre) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TipoIdentificacion.Nombre)
            </dd>
        </div>
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.Codigo) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Codigo)
            </dd>
        </div>
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.Identificacion) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Identificacion)
            </dd>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.NombreCompleto) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NombreCompleto)
            </dd>
        </div>
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.FechaNacimiento) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaNacimiento)
            </dd>
        </div>
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.Direccion) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion)
            </dd>
        </div>
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.FechaExpedicion) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaExpedicion)
            </dd>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.Email) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
        </div>
        <div class="col-3">
            <dt>
                @Html.DisplayNameFor(model => model.EmperesaDondeLabora) :
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EmperesaDondeLabora)
            </dd>
        </div>
        <div class="col-6">


        </div>
    </div>  
</div>
<hr />

<div>
    <div class="row">
        <div class="col-6">
            <div class="mb-3">
                <label class="form-label" for="codigo">
                    <strong>Listado Telefonico</strong>
                </label>
            </div>
            <table id="datatablesSimple" class="table ui-widget ui-widget-content">
                <thead>
                    <tr class="ui-widget-header">
                        <th>
                            Id
                        </th>
                        <th>
                            TipoTelefono
                        </th>
                        <th>
                            Numero
                        </th>
                        <th></th>
                        <th></th>
                    <tr />
                </thead>
                <tbody>
                    @foreach (var telefono in telefonos)
                    {
                        <tr>
                            <td>
                                @telefono.Id
                            </td>
                            <td>
                                @telefono.TipoTelefono.Nombre
                            </td>
                            <td>
                                @telefono.NumeroTelefonico
                            </td>
                            <td>
                                <button title="Editar telefono" class="btn btn-warning" onclick="editarPhone(@telefono.Id);">
                                    <i class="fa-solid fa-file-pen"></i>
                                </button>
                            </td>
                            <td>
                                <form action="@Url.Action("delete","phones")" onsubmit="return validar('Desea eliminar el cliente?')" method="post">
                                    <input type="hidden" value="@telefono.Id" name="id" />
                                    <input type="hidden" value="@telefono.ClienteId" name="ClienteId" />
                                    <button title="Eliminar" type="submit" class="btn btn-danger">
                                        <i class="fa-solid fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <div class="mb-3">
                <label class="form-label" for="codigo">
                    <strong>Referencias</strong>
                </label>
            </div>
            <table id="datatablesSimple2" class="table ui-widget ui-widget-content">
                <thead>
                    <tr class="ui-widget-header">
                        <th> Id</th>
                        <th>Tipo Identificacion</th>
                        <th>Identificacion</th>
                        <th>Nombre completo</th>
                        <th>Direccion</th>
                        <th>Email</th>
                        <th>Telefono</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var reference in Model.Referencias)
                    {
                        <tr>
                            <td>@reference.Id</td>
                            <td>@reference.TipoIdentificacion.Nombre</td>
                            <td>@reference.Identificacion</td>
                            <td>@reference.NombreCompleto</td>
                            <td>@reference.Direccion</td>
                            <td>@reference.Email</td>
                            <td>@reference.Telefono</td>
                            <td>
                                <button title="Editar referencia" class="btn btn-warning" onclick="editarReference(@reference.Id);">
                                    <i class="fa-solid fa-file-pen"></i>
                                </button>
                            </td>
                            <td>
                                <form action="@Url.Action("delete","References")" onsubmit="return validar('Desea eliminar el cliente?')" method="post">
                                    <input type="hidden" value="@reference.Id" name="id" />
                                    <input type="hidden" value="@reference.ClienteId" name="ClienteId" />
                                    <button title="Eliminar" type="submit" class="btn btn-danger">
                                        <i class="fa-solid fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

<p>
    <a title="Regresar" href="@Url.Action("index","client")" class="btn btn-primary">
        <i class="fa-solid fa-house"></i>
    </a>
    <button title="Agregar telefono" onclick="addPhone();" class="btn btn-secondary">
        <i class="fa-solid fa-phone"></i>
    </button>
    <button title="Agregar referencia" onclick="addReference();" class="btn btn-secondary">
        <i class="fa-solid fa-address-book"></i>
    </button>
</p>
<div id="references" title="Agregar o Editar referencias">
    <form id="referenceAdd" method="post" autocomplete="off" action="@Url.Action("create","references")">
        <input type="hidden" name="Id" value="0" id="Id" />
        <input type="hidden" name="ClienteId" value="@Model.Id" id="ClienteId" />
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Idemtificacion
            </label>
            <input type="text" class="form-control" name="Identificacion" id="Identificacion" />
        </div>
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Nombre
            </label>
            <input type="text" class="form-control" name="Nombre" id="Nombre" />
        </div>
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Apellido
            </label>
            <input type="text" class="form-control" name="Apellido" id="Apellido" />
        </div>
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Direccion
            </label>
            <input type="text" class="form-control" name="Direccion" id="Direccion" />
        </div>
        <div class="mb-3">
            <label class="form-label" for="email">
                Email
            </label>
            <input type="email" class="form-control" name="Email" id="Email" />
        </div>
        <div class="mb-3">
            <label class="form-label" accesskey="" for="codigo">
                Tipo de identificacion
            </label>
            <select name="TipoIdentificacionId" class="form-select" id="TipoIdentificacion">
                <option value="">Seleccione un tipo de identificacion</option>
                @foreach (var item in tipoIdentificaciones)
                {
                    <option value="@item.Id">@item.Nombre</option>
                }
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label" accesskey="" for="codigo">
                Telefono
            </label>
            <input type="text" class="form-control" name="Telefono" id="Telefono" />
        </div>
    </form>
</div>

<div id="phones" title="Agregar o Editar telefonos">
    <form id="PhoneAdd" method="post" autocomplete="off" action="@Url.Action("create","phones")">
        <input type="hidden" name="Id" value="0" id="Id" />
        <input type="hidden" name="ClienteId" value="@Model.Id" id="ClienteId" />
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Tipo de telefono
            </label>
            <select name="TipoTelefonoId" class="form-select" id="TipoTelefono">
                <option value="">Seleccione un tipo de telefono</option>
                @foreach (var item in tipoTelefonos)
                {
                    <option value="@item.Id">@item.Nombre</option>

                }
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Numero telefonico
            </label>
            <input type="text" name="NumeroTelefonico" value="" class="form-control" id="NumeroTelefonico">
        </div>
    </form>
</div>

EasyCredit/Views/Client/Index.cshtml
@model IEnumerable<DTO.ClienteDTO>

@{
    ViewBag.Title = "Index";
    List<Factory.Area> ListaArea = (List<Factory.Area>)ViewBag.Areas;
    List<Factory.TipoIdentificacion> ListaTipoIdentificacion = (List<Factory.TipoIdentificacion>)ViewBag.TipoIdentificaciones;
}

<h2>Listado de clientes</h2>

<p>
    <button title="Agregar cliente" id="createClient" class="btn btn-primary">
        <i class="fa-solid fa-user-plus"></i>
    </button>

</p>
<table id="datatablesSimple" class="table ui-widget ui-widget-content">
    <thead>
        <tr class="ui-widget-header">
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Identificacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreCompleto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmperesaDondeLabora)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaExpedicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoIdentificacionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AreaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ListaTelefono)
            </th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Identificacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmperesaDondeLabora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaNacimiento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaExpedicion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoIdentificacion.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Area.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ListaTelefono)
                </td>
                <td>
                    <button title="Editar cliente" class="btn btn-warning" onclick="editarCliente(@item.Id);">
                        <i class="fa-solid fa-file-pen"></i>
                    </button>
                </td>
                <td>
                    <a title="Detalle de cliente" href="@Url.Action("Details","client",new { id = item.Id })" class="btn btn-success">
                        <i class="fa-solid fa-eye"></i>
                    </a>
                </td>
                <td>
                    <form title="Eliminar" action="@Url.Action("delete","client")" onsubmit="return validar('Desea eliminar el cliente?')" method="post">
                        <input type="hidden" value="@item.Id" name="id" />
                        <button type="submit" class="btn btn-danger">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </form>
                </td>
                <td>
                    <a title="Prestamos" href="@Url.Action("index","loan", new { identificacion = item.Identificacion })" class="btn btn-info">
                        <i class="fa-solid fa-landmark"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>

</table>
<div id="clientes" title="Agregar o Editar clientes">
    <form id="clientAdd" method="post" autocomplete="off" action="@Url.Action("create","client")">
        <input type="hidden" name="Id" value="0" id="Id" />
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Identificacion
            </label>
            <input type="text" name="Identificacion" value="" class="form-control" id="Identificacion">
        </div>

        <div class="mb-3">
            <label class="form-label" for="nombre">
                fecha de expedicion
            </label>
            <input type="date" name="FechaExpedicion" value="" class="form-control" id="FechaExpedicion">
        </div>
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Codigo
            </label>
            <input type="text" name="Codigo" value="" class="form-control" id="Codigo">
        </div>
        <div class="mb-3">
            <label class="form-label" for="nombre">
                Nombre
            </label>
            <input type="text" name="Nombre" value="" class="form-control" id="Nombre">
        </div>
        <div class="mb-3">
            <label class="form-label" for="nombre">
                Apellido
            </label>
            <input type="text" name="Apellido" value="" class="form-control" id="Apellido">
        </div>
        <div class="mb-3">
            <label class="form-label" for="nombre">
                fecha de nacimiento
            </label>
            <input type="date" name="FechaNacimiento" value="" class="form-control" id="FechaNacimiento">
        </div>
        <div class="mb-3">
            <label class="form-label" for="nombre">
                Direccion
            </label>
            <input type="text" name="Direccion" value="" class="form-control" id="Direccion">
        </div>
        <div class="mb-3">
            <label class="form-label" for="nombre">
                Email
            </label>
            <input type="text" name="Email" value="" class="form-control" id="Email">
        </div>
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Emperesa donde labora
            </label>
            <input type="text" name="EmperesaDondeLabora" value="" class="form-control" id="EmperesaDondeLabora">

        </div>
        <div class="mb-3">
            <label class="form-label" for="codigo">
                Tipo identificacion
            </label>
            <select name="TipoIdentificacionId" class="form-select" id="TipoIdentificacion">
                <option value="">Seleccione un tipo de identificacion</option>
                @foreach (var item in ListaTipoIdentificacion)
                {
                    <option value="@item.Id">@item.Nombre</option>
                }
            </select>
        </div>

        <div class="mb-3">
            <label class="form-label" for="codigo">
                Sector
            </label>
            <select name="AreaId" class="form-select" id="Area">
                <option value="">Seleccione un sector</option>
                @foreach (var item in ListaArea)
                {
                    <option value="@item.Id">@item.Nombre</option>
                }
            </select>
        </div>

    </form>
</div>